### ISSUE TITLE
Problema ao clicar no ícone "x"

### ISSUE THREAD

**Issue by Izabella-Castro** [PedroBelo1550/Trabalho-Final-GCS#1]
Em todos os modais presentes na aplicação não funciona o ícone "X".

![0e4aa836-b238-4644-8d6b-ed680526c539](https://user-images.githubusercontent.com/70148656/228983072-b0dd5ce5-2d7e-4fb1-b475-a8c5502ef979.jpg)

**Comment by PedroBelo1550** [comment]
corrigido
